### ISSUE TITLE
Getting this exception while training

### ISSUE THREAD

**Issue by ankan97dutta** [shadow12138/faster-rcnn-keras#1]
2020-01-04 23:30:53.077035: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Epoch 1/40
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty
Exception: a must be non-empty

**Comment by shadow12138** [comment]
it should be caused by wrong image paths
make sure that image path in your annotation file is correct 
you can debug it by making a break point at utils/image_processing.py 31 line, if the img is not None, then you're getting the correct image path, it should work well then

**Comment by ankan97dutta** [comment]
I verified that img is not none still getting the issue.


Using TensorFlow backend.
Original image: height=676 width=934
Resized image:  height=300 width=414 C.im_size=300
Feature map size: height=18 width=25 C.rpn_stride=16
(1, 300, 414, 3)
2 includes 'y_rpn_cls' and 'y_rpn_regr'
Shape of y_rpn_cls (1, 18, 25, 18)
Shape of y_rpn_regr (1, 18, 25, 72)
{'filepath': 'J017.jpg', 'height': 676, 'width': 934, 'bboxes': [{'class': 'score_two', 'x1': 139, 'y1': 353, 'x2': 230, 'y2': 492}, {'class': 'score_four', 'x1': 86, 'y1': 149, 'x2': 
336, 'y2': 326}]}
Number of positive anchors for this image: 2
(array([ 6,  6,  9,  9, 11, 11]), array([ 7,  7, 16, 20,  5,  5]), array([ 8, 17,  7,  6,  3, 12]))
(array([ 6,  6,  6,  6, 11, 11, 11, 11]), array([7, 7, 7, 7, 5, 5, 5, 5]), array([32, 33, 34, 35, 12, 13, 14, 15]))
y_rpn_cls for possible pos anchor: [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
y_rpn_regr for positive anchor: [ 0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          1.          1.          1.
  1.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.         -0.58498132
  0.06184569 -1.96301365 -0.56687015]
Center position of positive anchor:  (112, 96)
Center position of positive anchor:  (80, 176)
Green bboxes is ground-truth bbox. Others are positive anchors
2020-01-05 22:02:20.449914: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Epoch 1/40
Exception: a must be non-empty
Exception: list assignment index out of range
Exception: a must be non-empty
Exception: a must be non-empty
Exception: list assignment index out of range
Exception: a must be non-empty
Exception: list assignment index out of range
Exception: a must be non-empty
Exception: a must be non-empty
Exception: list assignment index out of range

**Comment by shadow12138** [comment]
hey, i figured that's caused by wrong class_mapping,
i have changed my code a little in image_processing.py and config.py
please pull the latest code, and config the class_mapping in line 60 of config.py
if you have three classes, the class_mapping should go like {'class1': 0, 'class2': 1, 'class3': 2, 'bg':3}, where class1, class2 and class3 can be replaced with your own class name.

i have updated readme

**Comment by ankan97dutta** [comment]
I did change the class mapping before training
